**ACTIVIDAD AUTONOMA 3 - PROGRAMACION 2**

Nombre: Joel Adrian Sanchez Peña

**1. Creación del arreglo NumPy**

Crear un arreglo bidimensional llamado consumo con los datos de la
tabla.
Luego mostrar:
1. La matriz completa.
2. El número de dimensiones.
3. La forma del arreglo.
4. El número total de elementos.
5. El tipo de dato almacenado.



In [ ]:
# Importar la librería NumPy
import numpy as np

# Crear el arreglo bidimensional llamado consumo
consumo = np.array([
    [12.5, 13.0, 12.8, 14.1, 13.7, 6.2, 4.8],   #Computadoras
    [6.5, 6.8, 7.0, 6.9, 7.2, 3.1, 2.5],        #Laptops
    [18.0, 18.2, 18.1, 18.3, 18.4, 18.0, 17.9], #Servidor local
    [4.2, 4.1, 4.3, 4.4, 4.2, 4.0, 3.9],        # Red
    [9.0, 9.5, 9.2, 9.8, 10.0, 3.5, 2.0]        #Iluminacion
])

# Mostrar la matriz completa
print("Matriz completa:")
print(consumo)

# Mostrar el número de dimensiones
print("\nNumero de dimensiones:")
print(consumo.ndim)

# Mostrar la forma del arreglo
print("\nForma del arreglo:")
print(consumo.shape)

# Mostrar el número total de elementos
print("\nNumero total de elementos:")
print(consumo.size)

# Mostrar el tipo de dato almacenado
print("\nTipo de dato almacenado:")
print(consumo.dtype)

Matriz completa:
[[12.5 13.  12.8 14.1 13.7  6.2  4.8]
 [ 6.5  6.8  7.   6.9  7.2  3.1  2.5]
 [18.  18.2 18.1 18.3 18.4 18.  17.9]
 [ 4.2  4.1  4.3  4.4  4.2  4.   3.9]
 [ 9.   9.5  9.2  9.8 10.   3.5  2. ]]

Numero de dimensiones:
2

Forma del arreglo:
(5, 7)

Numero total de elementos:
35

Tipo de dato almacenado:
float64


**2. Análisis general del consumo**

Usando funciones de NumPy, calcular:
1. Consumo total semanal de todos los dispositivos.
2. Consumo promedio general.
3. Consumo máximo registrado.
4. Consumo mínimo registrado.
Después, escribir una interpretación breve sobre el comportamiento
general del consumo energético.

In [ ]:
#Consumo total semanal
total_consumo = np.sum(consumo)

#Promedio general
promedio_general = np.mean(consumo)

#Consumo maximo
consumo_maximo = np.max(consumo)

#Consumo minimo
consumo_minimo = np.min(consumo)

#Para poder tener solo dos decimales
resultado = round(promedio_general, 2)

print("Consumo total semanal:", total_consumo)
print("Consumo promedio general:", resultado)
print("Consumo máximo registrado:", consumo_maximo)
print("Consumo mínimo registrado:", consumo_minimo)

Consumo total semanal: 326.1
Consumo promedio general: 9.32
Consumo máximo registrado: 18.4
Consumo mínimo registrado: 2.0


**3. Análisis por dispositivo usando axis**

Calcular el consumo total semanal por cada dispositivo.
Luego responder:
1. ¿Qué dispositivo consumió más energía durante la semana?
2. ¿Qué dispositivo consumió menos energía durante la semana?
3. ¿Qué dispositivo mantiene un consumo más constante?
4. ¿Qué conclusión se puede obtener sobre el servidor local?

In [ ]:
# Lista de dispositivos
dispositivos = [
    "Computadoras",
    "Laptops",
    "Servidor local",
    "Red",
    "Iluminación"
]

# Consumo total por dispositivo
total_dispositivo = np.sum(consumo, axis=1)
# toda linea de redondeo la pongo para que no se haga molesto a la vista de ver tanto numero
total_redondeado = np.round(total_dispositivo, 2)
print("Consumo total semanal por dispositivo:\n")

for i in range(len(dispositivos)):
    print(dispositivos[i], ":", total_redondeado[i], "kWh")

Consumo total semanal por dispositivo:

Computadoras : 77.1 kWh
Laptops : 40.0 kWh
Servidor local : 126.9 kWh
Red : 29.1 kWh
Iluminación : 53.0 kWh


**¿Qué dispositivo consumió más energía durante la semana?**

El servicio local consumio mucho mas que los otros servicios en toda la semana

**¿Qué dispositivo consumió menos energía durante la semana?**

El serivicio de red fue el que menos energia consumio en toda la semana

**¿Qué dispositivo mantiene un consumo más constante?**

El servicio que mas se mantiene constante es el de servidor local por le hecho de que siempre me semante en 18 y solo varia decimalmente

**¿Qué conclusión se puede obtener sobre el servidor local?**

El servidor local se mira que siempre se mantiene el consumo incluso en fines de semana por lo que indica que debe permanecer funcionando siempre


**4. Análisis por día usando axis**

Calcular el consumo total por cada día de la semana.
Luego responder:
1. ¿Qué día tuvo mayor consumo energético?
2. ¿Qué día tuvo menor consumo energético?
3. ¿Qué diferencia se observa entre días laborables y fin de semana?
4. ¿Qué recomendación podría darse para optimizar el consumo?

In [ ]:
# Lista de días
dias = [
    "Lunes",
    "Martes",
    "Miércoles",
    "Jueves",
    "Viernes",
    "Sábado",
    "Domingo"
]

# Consumo total por día
total_dias = np.sum(consumo, axis=0)
total_dias_redondeado = np.round(total_dias, 2)
print("Consumo total por día:\n")

for i in range(len(dias)):
    print(dias[i], ":", total_dias_redondeado[i], "kWh")

Consumo total por día:

Lunes : 50.2 kWh
Martes : 51.6 kWh
Miércoles : 51.4 kWh
Jueves : 53.5 kWh
Viernes : 53.5 kWh
Sábado : 34.8 kWh
Domingo : 31.1 kWh


**¿Qué día tuvo mayor consumo energético?**

No fue solamente un dia, fueron 2 por lo que los dias jueves y viernes tienen un mayor consumo

**¿Qué día tuvo menor consumo energético?**

El dia que tuvo menor consumo fue el dia Domingo

**¿Qué diferencia se observa entre días laborables y fin de semana?**

Durante los dias laborables se puede visualizar que siempre habra un consumo más elevado por el hecho del uso constante de computadoras laptops e iluminación a diferencia del fin de semana que no se usan estos dispositivos


**¿Qué recomendación podría darse para optimizar el consumo?**

Como en todo lugar recomiendo que los equipos que no se usen se mantenga apagados o en modo reposo para bajar el consumo de energia


**5. Transformación del arreglo**

Transformar la matriz original en un arreglo unidimensional.
Luego:
1. Mostrar el arreglo transformado.
2. Verificar cuántos datos contiene.
3. Calcular nuevamente el promedio general.
4. Comparar este promedio con el obtenido desde la matriz original.
5. Explicar por qué ambos resultados coinciden.

In [ ]:
# Transformar arreglo a una dimensión
consumo_1d = consumo.flatten()

print("Arreglo transformado:")
print(consumo_1d)

# Número de datos
print("\nCantidad de datos:")
print(consumo_1d.size)

# Promedio general nuevamente
promedio_transformado = np.mean(consumo_1d)
nuevo_promedioxd = round(promedio_transformado, 2)

print("\nPromedio general:")
print(nuevo_promedioxd)

Arreglo transformado:
[12.5 13.  12.8 14.1 13.7  6.2  4.8  6.5  6.8  7.   6.9  7.2  3.1  2.5
 18.  18.2 18.1 18.3 18.4 18.  17.9  4.2  4.1  4.3  4.4  4.2  4.   3.9
  9.   9.5  9.2  9.8 10.   3.5  2. ]

Cantidad de datos:
35

Promedio general:
9.32


**Comparar este promedio con el obtenido desde la matriz original.**

Respuesta: Ambos promedios coinciden

**Explicar por qué ambos resultados coinciden.**

Respuesta: Resulta ser que ambos resultados son iguales por el hecho de que siguien siendo los mismo datos solo que ahora cambio la forma del arreglo y no los valores como tal.

**6. Mini análisis con condición**

Crear una condición para identificar los consumos mayores a 15 kWh.
Luego responder:
1. ¿Cuántos registros superan los 15 kWh?
2. ¿A qué dispositivo pertenecen principalmente esos valores?
3. ¿Qué indica esto sobre el patrón de consumo?

In [74]:

# Crear condición para consumos mayores a 15
mayores_15 = consumo > 15

# Obtener valores mayores a 15
valores_mayores = consumo[mayores_15]

# Cantidad de registros
print("\nCantidad de registros mayores a 15:")
print(valores_mayores.size)

# Mostrar qué dispositivo tiene esos consumos
print("\nLos dispositivos que con consumos mayores a 15 kWh pertenecen a: ")

for i in range(consumo.shape[0]):

    if np.any(consumo[i] > 15):
        print(dispositivos[i])


Cantidad de registros mayores a 15:
7

Los dispositivos que con consumos mayores a 15 kWh pertenecen a: 
Servidor local


**¿Cuántos registros superan los 15 kWh?**

Se registran 7 registros que superan los 15

**¿A qué dispositivo pertenecen principalmente esos valores?**
Todos los dispositivos pertecen al servidor local

**¿Qué indica esto sobre el patrón de consumo?**

Con lo que se puede identificar es que el servicio local matiene un consumo muy alto respecto a lo que es toda la semana